using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace SnailPet.Pipeline
{
    /// <summary>
    /// 생성 대상은 두 가지.
    ///  · GameData.g.cs — Unity 클라이언트용. 데이터를 코드에 그대로 박아 파싱을 없앤다.
    ///    행 수가 수백 단위라 코드로 들고 있는 편이 단순하고, 컴파일 타임에 타입이 검사된다.
    ///  · gamedata.json — 서버·툴용 이식 가능 사본.
    /// </summary>
    public static class CodeGen
    {
        public static string EmitCSharp(List<Table> tables, List<EnumDef> enums, IdRegistry ids)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   SnailData.xlsx 에서 자동 생성됨. 직접 수정하지 말 것.");
            sb.AppendLine("//   재생성: dotnet run --project Tools/DataPipeline");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace SnailPet.Data");
            sb.AppendLine("{");

            foreach (var e in enums)
            {
                sb.AppendLine($"    public enum {e.Name}");
                sb.AppendLine("    {");
                foreach (var (name, value) in e.Members)
                    sb.AppendLine($"        {Safe(name)} = {value},");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            foreach (var t in tables)
            {
                sb.AppendLine($"    public sealed class {RowClass(t.Name)}");
                sb.AppendLine("    {");
                foreach (var c in t.Columns)
                    sb.AppendLine($"        public readonly {c.Type.CsType} {Safe(c.Name)};");
                sb.AppendLine();
                sb.Append($"        public {RowClass(t.Name)}(");
                for (int i = 0; i < t.Columns.Count; i++)
                    sb.Append((i > 0 ? ", " : "") + t.Columns[i].Type.CsType + " " + Camel(t.Columns[i].Name));
                sb.AppendLine(")");
                sb.AppendLine("        {");
                foreach (var c in t.Columns)
                    sb.AppendLine($"            {Safe(c.Name)} = {Camel(c.Name)};");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("    public static class GameData");
            sb.AppendLine("    {");

            foreach (var t in tables)
            {
                string cls = RowClass(t.Name);
                sb.AppendLine($"        public static readonly {cls}[] {t.Name} = new {cls}[]");
                sb.AppendLine("        {");
                for (int r = 0; r < t.Rows.Count; r++)
                {
                    sb.Append($"            new {cls}(");
                    for (int i = 0; i < t.Columns.Count; i++)
                    {
                        if (i > 0) sb.Append(", ");
                        sb.Append(Literal(t.Columns[i], Program.Get(t.Rows[r], t.Columns[i].Index), ids));
                    }
                    sb.AppendLine("),");
                }
                sb.AppendLine("        };");
                sb.AppendLine();
            }

            // Id 로 바로 찾을 수 있게. Id 가 행마다 유일한 테이블에만 만든다.
            foreach (var t in tables)
            {
                var idCol = t.Columns.Find(c => c.Name == "Id" && c.Type.Kind == FieldKind.Int);
                if (idCol == null) continue;
                if (!IdIsUnique(t, idCol)) continue;

                string cls = RowClass(t.Name);
                sb.AppendLine($"        public static readonly Dictionary<int, {cls}> {t.Name}ById = Build{t.Name}ById();");
                sb.AppendLine($"        private static Dictionary<int, {cls}> Build{t.Name}ById()");
                sb.AppendLine("        {");
                sb.AppendLine($"            var d = new Dictionary<int, {cls}>({t.Name}.Length);");
                sb.AppendLine($"            foreach (var row in {t.Name}) d[row.Id] = row;");
                sb.AppendLine("            return d;");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            // 토큰 이름 ↔ ID. 로그와 디버깅에서 [상추] 를 다시 보려면 필요하다.
            sb.AppendLine("        /// <summary>[토큰] → ID. 번호는 세이브 데이터와 묶이므로 재배치 금지.</summary>");
            sb.AppendLine("        public static readonly Dictionary<string, int> IdByToken = new Dictionary<string, int>");
            sb.AppendLine("        {");
            foreach (var kv in SortedById(ids))
                sb.AppendLine($"            {{ {Quote(kv.Key)}, {kv.Value} }},");
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        public static readonly Dictionary<int, string> TokenById = BuildTokenById();");
            sb.AppendLine("        private static Dictionary<int, string> BuildTokenById()");
            sb.AppendLine("        {");
            sb.AppendLine("            var d = new Dictionary<int, string>(IdByToken.Count);");
            sb.AppendLine("            foreach (var kv in IdByToken) d[kv.Value] = kv.Key;");
            sb.AppendLine("            return d;");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string EmitJson(List<Table> tables, List<EnumDef> enums, IdRegistry ids)
        {
            var sb = new StringBuilder();
            sb.AppendLine("{");
            sb.AppendLine($"  \"generatedAt\": {Quote(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"))},");
            sb.AppendLine("  \"source\": \"SnailData.xlsx\",");

            sb.AppendLine("  \"enums\": {");
            for (int e = 0; e < enums.Count; e++)
            {
                sb.Append($"    {Quote(enums[e].Name)}: {{");
                for (int i = 0; i < enums[e].Members.Count; i++)
                    sb.Append((i > 0 ? ", " : "") + Quote(enums[e].Members[i].name) + ": " + enums[e].Members[i].value);
                sb.AppendLine("}" + (e < enums.Count - 1 ? "," : ""));
            }
            sb.AppendLine("  },");

            sb.AppendLine("  \"idByToken\": {");
            var idList = SortedById(ids);
            for (int i = 0; i < idList.Count; i++)
                sb.AppendLine($"    {Quote(idList[i].Key)}: {idList[i].Value}" + (i < idList.Count - 1 ? "," : ""));
            sb.AppendLine("  },");

            sb.AppendLine("  \"tables\": {");
            for (int ti = 0; ti < tables.Count; ti++)
            {
                var t = tables[ti];
                sb.AppendLine($"    {Quote(t.Name)}: [");
                for (int r = 0; r < t.Rows.Count; r++)
                {
                    sb.Append("      {");
                    for (int i = 0; i < t.Columns.Count; i++)
                    {
                        if (i > 0) sb.Append(", ");
                        sb.Append(Quote(t.Columns[i].Name) + ": " +
                                  JsonValue(t.Columns[i], Program.Get(t.Rows[r], t.Columns[i].Index), ids));
                    }
                    sb.AppendLine("}" + (r < t.Rows.Count - 1 ? "," : ""));
                }
                sb.AppendLine("    ]" + (ti < tables.Count - 1 ? "," : ""));
            }
            sb.AppendLine("  }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static List<KeyValuePair<string, int>> SortedById(IdRegistry ids)
        {
            var list = new List<KeyValuePair<string, int>>(ids.Map);
            list.Sort((a, b) => a.Value.CompareTo(b.Value));
            return list;
        }

        private static string Literal(Column c, string v, IdRegistry ids)
        {
            bool empty = string.IsNullOrEmpty(v);

            switch (c.Type.Kind)
            {
                case FieldKind.Int:
                    if (empty) return "0";
                    return IdRegistry.IsToken(v) ? ids.Resolve(v).ToString() : int.Parse(v).ToString();

                case FieldKind.NullableInt:
                    if (empty) return "null";
                    return IdRegistry.IsToken(v) ? ids.Resolve(v).ToString() : int.Parse(v).ToString();

                case FieldKind.Double:
                case FieldKind.NullableDouble:
                    if (empty) return c.Type.Kind == FieldKind.Double ? "0d" : "null";
                    return double.Parse(v, NumberStyles.Any, CultureInfo.InvariantCulture)
                                 .ToString("R", CultureInfo.InvariantCulture) + "d";

                case FieldKind.Bool:
                    return (!empty && Values.TryParseBool(v, out bool b) && b) ? "true" : "false";

                case FieldKind.DateTime:
                    if (empty || !Values.TryParseDate(v, out var dt)) return "default(System.DateTime)";
                    return $"new System.DateTime({dt.Year}, {dt.Month}, {dt.Day}, {dt.Hour}, {dt.Minute}, {dt.Second})";

                case FieldKind.Enum:
                    return empty ? $"default({c.Type.EnumName})" : $"{c.Type.EnumName}.{Safe(v)}";

                case FieldKind.ListInt:
                {
                    var items = Values.SplitList(v);
                    if (items.Length == 0) return "System.Array.Empty<int>()";
                    var sb = new StringBuilder("new int[] { ");
                    for (int i = 0; i < items.Length; i++)
                        sb.Append((i > 0 ? ", " : "") +
                                  (IdRegistry.IsToken(items[i]) ? ids.Resolve(items[i]).ToString() : items[i]));
                    return sb.Append(" }").ToString();
                }

                case FieldKind.ListString:
                {
                    var items = Values.SplitList(v);
                    if (items.Length == 0) return "System.Array.Empty<string>()";
                    var sb = new StringBuilder("new string[] { ");
                    for (int i = 0; i < items.Length; i++)
                        sb.Append((i > 0 ? ", " : "") + Quote(items[i]));
                    return sb.Append(" }").ToString();
                }

                default:
                    return empty ? "null" : Quote(v);
            }
        }

        private static string JsonValue(Column c, string v, IdRegistry ids)
        {
            bool empty = string.IsNullOrEmpty(v);

            switch (c.Type.Kind)
            {
                case FieldKind.Int:
                case FieldKind.NullableInt:
                    if (empty) return c.Type.Kind == FieldKind.Int ? "0" : "null";
                    return IdRegistry.IsToken(v) ? ids.Resolve(v).ToString() : int.Parse(v).ToString();

                case FieldKind.Double:
                case FieldKind.NullableDouble:
                    if (empty) return c.Type.Kind == FieldKind.Double ? "0" : "null";
                    return double.Parse(v, NumberStyles.Any, CultureInfo.InvariantCulture)
                                 .ToString("R", CultureInfo.InvariantCulture);

                case FieldKind.Bool:
                    return (!empty && Values.TryParseBool(v, out bool b) && b) ? "true" : "false";

                case FieldKind.DateTime:
                    return (!empty && Values.TryParseDate(v, out var dt))
                         ? Quote(dt.ToString("yyyy-MM-ddTHH:mm:ss")) : "null";

                case FieldKind.Enum:
                    return empty ? "null" : Quote(v);

                case FieldKind.ListInt:
                {
                    var items = Values.SplitList(v);
                    var sb = new StringBuilder("[");
                    for (int i = 0; i < items.Length; i++)
                        sb.Append((i > 0 ? ", " : "") +
                                  (IdRegistry.IsToken(items[i]) ? ids.Resolve(items[i]).ToString() : items[i]));
                    return sb.Append("]").ToString();
                }

                case FieldKind.ListString:
                {
                    var items = Values.SplitList(v);
                    var sb = new StringBuilder("[");
                    for (int i = 0; i < items.Length; i++)
                        sb.Append((i > 0 ? ", " : "") + Quote(items[i]));
                    return sb.Append("]").ToString();
                }

                default:
                    return empty ? "null" : Quote(v);
            }
        }

        /// <summary>뽑기 테이블처럼 같은 Id 가 여러 행에 걸치는 시트는 딕셔너리를 만들 수 없다.</summary>
        private static bool IdIsUnique(Table t, Column idCol)
        {
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var row in t.Rows)
            {
                string v = Program.Get(row, idCol.Index);
                if (v.Length == 0) return false;
                if (!seen.Add(v)) return false;
            }
            return true;
        }

        private static string RowClass(string table) => table + "Row";

        /// <summary>C# 식별자로 쓸 수 있게 다듬는다. 한글 식별자는 C# 에서 합법이다.</summary>
        private static string Safe(string s)
        {
            if (string.IsNullOrEmpty(s)) return "_";
            var sb = new StringBuilder();
            foreach (char ch in s)
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        private static string Camel(string s)
        {
            string t = Safe(s);
            return char.IsUpper(t[0]) ? char.ToLowerInvariant(t[0]) + t.Substring(1) : "_" + t;
        }

        private static string Quote(string s)
        {
            var sb = new StringBuilder("\"");
            foreach (char ch in s)
            {
                switch (ch)
                {
                    case '"':  sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\n': sb.Append("\\n");  break;
                    case '\r': sb.Append("\\r");  break;
                    case '\t': sb.Append("\\t");  break;
                    default:   sb.Append(ch);     break;
                }
            }
            return sb.Append('"').ToString();
        }
    }
}
